name: Sync and merge upstream repository with your current repository
description: Syncs and merges your current repository with the upstream repository. Fork of https://github.com/mheene/sync-upstream-repo.
author: Dabreadman

inputs:
  mode:
    description: > 
        "The mode the action will run on. There only two mode supported, "branch-to-branch\": all the commits from the upstream branch will be synched into the downstream branch using the defined merge strategy
        "release-following" : detects if a newer branch matching the pattern defined in UPSTREAM_BRANCH is created and renames the current DOWNSTREAM_BRANCH 
        to the previous branch name and continues to synch the commits from the new upstream branch to DOWNSTREAM_BRANCH"
    required: true
  upstream_repo_url:
    description: URL of GitHub public upstream repo
    required: true
  upstream_branch:
    description: Branch to merge from upstream (defaults to downstream branch)
    required: false
    default: "main"
  downstream_repo_url:
    description: URL of the GitHub repo from upstream
    required: true
  downstream_branch:
    description: Branch to merge into downstream, if not provided it will default to the upstream branch name
    required: false
    default: ""
  token:
    description: GitHub Bot token
    required: true
    default: ${{ github.token }}
  merge_strategy:
    description: Merge strategy, controls which git operation (rebase or merge) will be used to synch with upstream. The values allowed are either "rebase" or "merge", with "rebase" being the default.
    required: false
    default: "release"
  spawn_logs:
    description: Create a marker commit in the downstream branch to signal creation of commit. The allowed values are either `true` or `false`, with default being false.
    required: false
    default: "false"
  
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--mode"
    - ${{ inputs.mode }}
    - "--upstream-repo-url"
    - ${{ inputs.upstream_repo_url }}
    - "--upstream-branch"
    - ${{ inputs.upstream_branch }}
    - "--downstream-repo-url"
    - ${{ inputs.downstream_repo_url }}
    - "--downstream-branch"
    - ${{ inputs.downstream_branch }}
    - "--token"
    - ${{ inputs.token }}
    - "--merge-strategy"
    - ${{ inputs.merge_strategy }}
    - "--spawn-logs"
    - ${{ inputs.spawn_logs}}
  
branding:
  icon: "git-merge"
  color: "blue"
